on: [push]
jobs:
  build-img:
    runs-on: ubuntu-latest
    steps:
      - name: "setup depends"
        run: |
          sudo apt-get -y update
          sudo apt-get install -y build-essential git nasm
          echo "eval \"$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)\"" >> ~/.bashrc
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          sudo apt-get install -y grub-pc-bin xorriso mtools grub-efi-amd64-bin
          brew install i686-elf-gcc

      - name: "download source code"
        run: git clone https://github.com/Alonecoder2011/devOS && cd devOS

      - name: "prepare for build"
        run: cd devOS && chmod +x ./util/*.sh
      
      - name: "build devOS (LEGACY)"
        run: |
          echo "eval \"$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)\"" >> ~/.bashrc
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          cd devOS && ./util/mkkernel.sh --buildrun

      - name: "build devOS (MULTIBOOT)"
        run: |
          echo "eval \"$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)\"" >> ~/.bashrc
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          cd devOS && ./util/mkkernel-mb.sh --buildrun
      
      - name: "upload devOS.bin"
        uses: actions/upload-artifact@v4
        with:
          name: devOS.bin
          path: ./devOS/bin/devOS.bin

      - name: "upload multiboot kernel"
        uses: actions/upload-artifact@v4
        with:
          name: multiboot_kernel
          path: ./devOS/bin/multiboot_kernel

      - name: "upload devOS.iso"
        uses: actions/upload-artifact@v4
        with:
          name: devOS_hybrid_x86.iso
          path: ./devOS/bin/devOS.iso
